version: '2'

networks:
  default:
    external:
      name: bridge

services: 
  cnt7-dev:
    build: ./
    image: gse/cnt7-dev
    network_mode: bridge
    volumes:
      - ~/IdeaProjects:/root/dev


